"""add task groups

Revision ID: fc6ccbf6ed99
Revises: d4a32b801a7b
Create Date: 2026-03-30 22:22:26.701478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc6ccbf6ed99'
down_revision: Union[str, Sequence[str], None] = 'd4a32b801a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_groups_id'), 'task_groups', ['id'], unique=False)
    op.create_index(op.f('ix_task_groups_name'), 'task_groups', ['name'], unique=False)
    op.add_column('tasks', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'task_groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'group_id')
    op.drop_index(op.f('ix_task_groups_name'), table_name='task_groups')
    op.drop_index(op.f('ix_task_groups_id'), table_name='task_groups')
    op.drop_table('task_groups')
    # ### end Alembic commands ###
